Feature/elevator
MineCountry/CityBuild pull request #15
Opened 2024-02-25 16:23 UTC by MerryDev

# Zusammenfassung
Diese PR fügt Aufzüge über Daylight-Sensoren in Minecraft hinzu. Dazu müssen lediglich zwei Blöcke über dem Sensor jeweils frei sein.
___

## Minecraft
* Aufzüge

<br>

## Developer
Keine Änderungen

<br>

### Neu hinzugefügte Repositories
Keine Änderungen
  
<br>

### Neu hinzugefügte Abhängigkeiten
Keine Änderungen
___

## Anmerkungen
Keine Anmerkung

___
## Issue-Tracking
Bitte melde alle Fehler oder andere Vorschläge [hier](https://quantraxnet.youtrack.cloud/issues/CB).
___

2024-02-25 18:13 UTC, ExceptionThread requested changes, later dismissed

2024-02-25 18:13 UTC, ExceptionThread commented on src/main/java/net/quantrax/citybuild/listener/ElevatorListener.java
> +        if (location.getBlock().getType() != Material.DAYLIGHT_DETECTOR) return;
```suggestion
        if ((!event.isSneaking())
        || if (!location.getWorld().getName().equalsIgnoreCase(worldName)) 
        || if (location.getBlock().getType() != Material.DAYLIGHT_DETECTOR)) {
        return;
        }
```

2024-03-04 18:16 UTC, ExceptionThread requested changes

2024-03-04 18:16 UTC, ExceptionThread commented on src/main/java/net/quantrax/citybuild/listener/ElevatorListener.java
> +        if (location.getBlock().getType() != Material.DAYLIGHT_DETECTOR) return;
Als ein If Statement wäre noch schön :)

2024-03-04 18:16 UTC, ExceptionThread commented on src/main/java/net/quantrax/citybuild/listener/ElevatorListener.java
> +        if (location.getBlock().getType() != Material.DAYLIGHT_DETECTOR) return;
Hier ebenso

2024-03-04 18:16 UTC, ExceptionThread commented on src/main/java/net/quantrax/citybuild/listener/ElevatorListener.java
> +        UP, DOWN
```suggestion
    private enum Direction {
        UP, 
        DOWN
```

2024-03-04 18:46 UTC, MerryDev commented on src/main/java/net/quantrax/citybuild/listener/ElevatorListener.java
> +        if (location.getBlock().getType() != Material.DAYLIGHT_DETECTOR) return;
Sehe ich persönlich jetzt anders. Sind ja drei logisch voneinander unabhängigen und thematisch differenzierte Bedingungen. Bei ähnlichen inhaltlichen Abfragen oder zwei kurzen logisch verknüpften Bedingungen lasse ich mir das noch eingehen das als ein Statement zu schreiben, aber bei drei finde ich das dann schon ein wenig too much.

2024-03-04 18:48 UTC, MerryDev commented on src/main/java/net/quantrax/citybuild/listener/ElevatorListener.java
> +        if (location.getBlock().getType() != Material.DAYLIGHT_DETECTOR) return;
Siehe anderen Kommentar (hier wegen nicht inhaltlich ähnlichen Bedingungen).

2024-03-04 18:59 UTC, TheMiCraft approved these changes

2024-03-04 19:39 UTC, ExceptionThread commented on src/main/java/net/quantrax/citybuild/listener/ElevatorListener.java
> +        if (location.getBlock().getType() != Material.DAYLIGHT_DETECTOR) return;
sieht halt Formattechnisch trash dann aus aber dann mach halt so

2024-03-04 19:39 UTC, ExceptionThread approved these changes

2024-03-04 19:50 UTC, merged